### ISSUE TITLE
Indexing fails with FileNotFoundException

### ISSUE THREAD

**Issue by praseodym** [McGill-DMaS/Kam1n0-Community#4] opened 2015-09-28 12:21 UTC
First of all, thanks for this project! It looks very promising.

I'm trying to run Kam1n0 with the provided libpng and zlib dll files. After manually configuring my IDA Pro path in `kam1n0-conf.xml`, my IDA installation is found, but indexing fails with the following error:

```
[ERROR] 09-28 14:14:28.228 ca.mcgill.sis.dmas.kam1n0.framework.disassembly.DisassemblyFactory [DefaultQuartzScheduler_Worker-1] DisassemblyFactory - Failed to parse the assembly file.
 java.io.FileNotFoundException: C:\ProgramData\Kam1n0-data\tmp\admin\libpng-1.7.0b54.dll.tmp (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_60]
        at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_60]
        at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_60]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:127) ~[Kam1n0-0.1.0.jar:?]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:117) ~[Kam1n0-0.1.0.jar:?]
        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:404) ~[Kam1n0-0.1.0.jar:?]
        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:99) ~[Kam1n0-0.1.0.jar:?]
        at com.google.common.io.CharSource.readLines(CharSource.java:198) ~[Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.io.LinesOnRAM.<init>(LinesOnRAM.java:34) ~[Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.io.Lines.fromFileFullyCached(Lines.java:39) ~[Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.load(DisassemblyFactoryIDA.java:126) [Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.kam1n0.deamon.LSHMR.FunctionCloneSearchServiceProvider_LSH_MR.diassemble(FunctionCloneSearchServiceProvider_LSH_MR.java:219) [Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.kam1n0.deamon.LSHMR.BinaryIndexProcedureLSHMR.execute(BinaryIndexProcedureLSHMR.java:53) [Kam1n0-0.1.0.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [Kam1n0-0.1.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [Kam1n0-0.1.0.jar:?]
[ERROR] 09-28 14:14:28.245 ca.mcgill.sis.dmas.kam1n0.deamon.LSHMR.BinaryIndexProcedureLSHMR [DefaultQuartzScheduler_Worker-1] BinaryIndexProcedureLSHMR - Failed to process the IndexBinary job from admin
 java.lang.Exception: Failed to disasemble the given file.
        at ca.mcgill.sis.dmas.kam1n0.impl.disassembly.DisassemblyFactoryIDA.load(DisassemblyFactoryIDA.java:142) ~[Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.kam1n0.deamon.LSHMR.FunctionCloneSearchServiceProvider_LSH_MR.diassemble(FunctionCloneSearchServiceProvider_LSH_MR.java:219) ~[Kam1n0-0.1.0.jar:?]
        at ca.mcgill.sis.dmas.kam1n0.deamon.LSHMR.BinaryIndexProcedureLSHMR.execute(BinaryIndexProcedureLSHMR.java:53) [Kam1n0-0.1.0.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [Kam1n0-0.1.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [Kam1n0-0.1.0.jar:?]
```

A similar error occurs for the zlib dll. The tmp folder contains the following files, i.e. no `.tmp` files:

```
 Directory of C:\ProgramData\Kam1n0-data\tmp\admin

28-09-2015  14:14           195.072 libpng-1.7.0b54.dll
28-09-2015  14:14           335.872 libpng-1.7.0b54.id0
28-09-2015  14:14           761.856 libpng-1.7.0b54.id1
28-09-2015  14:14                47 libpng-1.7.0b54.id2
28-09-2015  14:14            16.384 libpng-1.7.0b54.nam
28-09-2015  14:14               501 libpng-1.7.0b54.til
```

**Comment by steven-hh-ding** [comment] 2015-10-04 03:16
Hi praseodym,

This issue has been resolved and you are able to index binaries at the admin page now. It is caused by the space in the installation path. The released installer has been updated, and please make sure you have uninstalled previous installation of Kam1n0. Now you don't need to manually update the $IDA_PATH$ as the installer will do the job. 

Thanks,

Steven

**Closed as completed** 2015-10-05 12:53 UTC

**Comment by praseodym** [comment] 2015-10-05 13:08
Thanks! Now indexing a new binary works as it should. However, IDA doesn't seem to want to talk to Kam1n0 just yet. I'll open a new issue for that.
